### ISSUE TITLE
data usage and syncing

### ISSUE THREAD

**Issue by spamwax** [maxpower47/PinDroid#12]
Does PinDroid do a full sync of all bookmarks regardless of if they've been modified on either Pinboard servers or the phone?

With about 1700 bookmarks and a 12hr sync interval, Pinboard has used about [43 MB of data](https://dl.dropboxusercontent.com/u/675947/Misc/Pindroid_Data_Usage.png) in less than a week!
is this normal?

**Comment by spamwax** [comment]
I am reopening this as PinDroid is still using a lot of data given the number of bookmarks I have.
Is there a possibility to add an option to only do manual syncing.
The attached screenshot is for a period where I just used it at bookmarks and no web viewing was done using the app

**Comment by bastibe** [comment]
Pindroid is using 200 MB per month here, too. That's way too much for just syncing a few bookmarks.

Do you, by any chance, do a big sync on every share sheet interaction?
