### ISSUE TITLE
Feature request: Tasker/Locale pluging for sync

### ISSUE THREAD

**Issue by khinsen** [maxpower47/PinDroid#16]
Background: I use Tasker for energy management on my phone. One important element is keeping data connections (GSM and Wifi) off most of the time. It's enabled once per hour for a few minutes, to fetch mail, sync data, etc.

This doesn't work with PinDroid because I can't when a sync is started. I end up having to sync manually.

The best solution would be a plugin for Tasker (and API-compatible apps, such as Locale), which lets me launch a sync as part of my once-per-hour network session.

**Comment by maxpower47** [comment]
This happens automatically now in marshmallow with doze.  PinDroid should only sync during doze maintenance windows.
