### ISSUE TITLE
Bookmark and Read Later icons are the same

### ISSUE THREAD

**Issue by xiongchiamiov** [maxpower47/PinDroid#23]
Mobile Firefox keeps the two most recently-used share targets [at the top of the context menu](https://mozorg.cdn.mozilla.net/media/img/l10n/en-US/firefox/android/customize/desktop-sharing.acb8d45259db.jpg).  However, if you're like me, those two are always both PinDroid: the normal bookmark saving and the read-later functionality.  The problem is that those two use the same icon, which makes it impossible to tell which one you're clicking - you've just got to guess and find out if you're lucky. :)

**Comment by xiongchiamiov** [comment]
@ChangeTip, send 1 beer to @maxpower47.  Thanks!

**Comment by changetip** [comment]
Hi @maxpower47, @xiongchiamiov sent you a Bitcoin tip worth 1 beer (13,490 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/859734)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
