### ISSUE TITLE
Return to origin after sharing with Pindroid

### ISSUE THREAD

**Issue by joweiser** [maxpower47/PinDroid#27]
After using the share intent to store an URL in Pindroid it should return to the origin of the intent instead of opening the Pindroid main screen.

**Comment by joweiser** [comment]
I recently saw another application that stays withing itself after using its intent to share something. What do others think about this?

**Comment by maxpower47** [comment]
1732a0ebd27567feee20c50fe32261b32aadd697 fixes this so the add bookmark activity in the only thing involved in sharing a bookmark, so when it finishes it returns to wherever you just were.
