### ISSUE TITLE
Marshmallow Sharing 

### ISSUE THREAD

**Issue by dshanske** [maxpower47/PinDroid#40]
Since moving to Marshmallow, every time I share to Pindroid it is asking me to select an account.

**Comment by noamross** [comment]
Same.  +1

**Comment by tseven** [comment]
I'm experiencing the same issue. 
Nexus 6p running 6.0.1.

I have multiple Google accounts but only one is associated and syncing to pinboard. 

After pressing share pinboard presents a popup asking which account should be used. The two options are my account and "add account".

**Comment by maxpower47** [comment]
This is fixed in b0b71e650d516d261760c05d7a932548f2a7ac67.  

3.1.1 has been published to the play store and will be available shortly.

**Comment by dshanske** [comment]
Thank you. That was driving me crazy.
