### ISSUE TITLE
Tablet mode on Android N

### ISSUE THREAD

**Issue by andreiluca** [maxpower47/PinDroid#53]
When I set the display size in Android N DP4 to small it goes to tablet mode. Likely wrong DPI setup.
Thank you for the awesome Pinboard client and keep up the good work!

**Comment by materemias** [comment]
Having a preference to force phone layout or tablet layout would be great

**Comment by kLy** [comment]
Yes this would be really useful! As it is things get displayed with half the screen size:
https://goo.gl/photos/RUGgZNJaJcPRGTm57

**Comment by materemias** [comment]
Duplicate of #62
