### ISSUE TITLE
Text wrapping issue with over a hundred bookmarks

### ISSUE THREAD

**Issue by agostonbarna** [maxpower47/PinDroid#68]
Custom DPI:
![screenshot_20170211-134043](https://cloud.githubusercontent.com/assets/5561396/22853869/1f397fb6-f061-11e6-9025-315b587c2c81.png)

Default DPI:
![screenshot_20170211-134015](https://cloud.githubusercontent.com/assets/5561396/22853846/8b191dc8-f060-11e6-8ee0-18bd83a1b7e2.png)

Device: OnePlus 3
Android version: 7.0

**Comment by spl** [comment]
I encountered this, too, on a Moto G5 Plus.
