### ISSUE TITLE
Suggested Tags Always Suggest the same Useless Tags

### ISSUE THREAD

**Issue by overtones99** [maxpower47/PinDroid#75]
I've been using PinDroid for a couple years, and not once has the 'suggested-tags' field successfully suggested a tag. Instead it displays the same weird set of tags that have nothing to do with the content of the page:

ifttt twitter facebook WSH
objective-C twitterlink 1960s
@codepo8 Aiviq art

Is there a solution for this?
When i used to use Delicious, the suggested tags feature was pretty great, and saved me a lot of time, plus suggested tags that I wouldn't have thought of using.

**Comment by maxpower47** [comment]
The tag suggestions come from a pinboard API call, I don't have any control over what it suggests.  You can contact their support at support@pinboard.in if you'd like to open an issue for them to investigate.
