### ISSUE TITLE
syncing seemed to have stopped working since yesterday

### ISSUE THREAD

**Issue by RMHogervorst** [maxpower47/PinDroid#96]
Hi there. It seems the sync of the app is failing. Is there something I can do to help debug?

**Comment by RMHogervorst** [comment]
Yesus C. It was medium!

**Comment by owenblacker** [comment]
@RMHogervorst What solved this for you? Syncing has stopped for me too…

**Comment by RMHogervorst** [comment]
I modified the titles from some medium articles. Those articles had embedded JavaScript or something in their titles. Once i removed that, syncing worked again

**Comment by owenblacker** [comment]
There was a Medium post in my queue, but my problem predates that and fixing the wacky embed in that bookmark (indeed, deleting it and re-adding it more carefully) doesn't seem to have fixed it 😣
